#!/bin/sh

mkdir -p /var/run/tor
cp /usr/local/etc/tor/torrc /var/run/tor
chmod a-wx,go-rwx /var/run/tor/torrc
chown -R tor:tor /var/run/tor

exec 2>&1
exec -P -u tor:tor /usr/local/bin/tor -f /var/run/tor/torrc
